#ifndef ESTRUCTURAS_UTILS_H
#define ESTRUCTURAS_UTILS_H

typedef enum {
    // HANDSHAKES
    HANDSHAKE_STORAGE,
    HANDSHAKE_WORKER,
    HANDSHAKE_QUERY_CONTROL,
    HANDSHAKE_MASTER,
    HANDSHAKE_OK,
    HANDSHAKE_ERROR,

    // HEADERS QUE RECIBE STORAGE
    CREATE_FILE,
    TRUNCATE_FILE,
    TAG_FILE,
    COMMIT_TAG,
    WRITE_BLOCK,
    READ_BLOCK,
    REMOVE_TAG,

    //HEADERS QUE RECIBE EL MASTER
    QUERY_FINALIZADA,        // Worker → Master
    RESPUESTA_LECTURA,       // Worker → Master

    LECTURA_REALIZADA,
    DESALOJO_QUERY,

    // HEADERS QUE RECIBE WORKER
    RESPUESTA_CREATE_FILE,
    RESPUESTA_TRUNCATE_FILE,
    RESPUESTA_TAG_FILE,
    RESPUESTA_COMMIT_TAG,
    RESPUESTA_WRITE_BLOCK,
    RESPUESTA_READ_BLOCK,
    RESPUESTA_REMOVE_TAG,
    ERROR_OPERACION,
    EJECUTAR_QUERY,          // Master → Worker
    DESALOJAR_QUERY,         // Master → Worker
    WORKER_LIBRE,
    

    //HEADERS QUE RECIBE QUERY CONTROL
    QC_LECTURA,             //Master → Query Control
    QC_FINALIZACION,        //Master → Query Control

} t_header;

typedef enum{
    INSTRUCCION_CREATE,
    INSTRUCCION_TRUNCATE,
    INSTRUCCION_WRITE,
    INSTRUCCION_READ,
    INSTRUCCION_TAG,
    INSTRUCCION_COMMIT,
    INSTRUCCION_FLUSH,
    INSTRUCCION_DELETE,
    INSTRUCCION_END,
} t_tipo_instruccion;

typedef enum{
    COMPLETADA,
    DESCONEXION_WORKER,
    DESCONEXION_STORAGE,
}t_motivo_de_finalizacion_de_query_control;

typedef enum {
    FINALIZACION_EXITOSA,
    ERROR_DESCONEXION_WORKER,
    ERROR_DESCONEXION_QUERY_CONTROL,
    ERROR_EJECUCION
} t_motivo_finalizacion;
#endif